### ISSUE TITLE
Skil 1

### ISSUE THREAD

**Issue by sigruntinna** [SenpaiPlz/0011Week#1]
**Í þessum hluta skal skrifa console forrit með eftirfarandi kröfur til virkni:**

_(10%) Notandi skal geta skráð þekktar persónur úr sögu tölvunarfræðinnar. Að lágmarki skal vera    hægt að skrá eftirfarandi gögn um sérhverja persónu: nafn, kyn, fæðingarár og dánarár (ef við á)._
- viljum geta editað
- skrifa sér klasa fyrir persónuupplýsingar

_(10%) Forritið skal geta birt lista af þeim persónum sem skráðar hafa verið._
_(10%) Forritið skal geyma listann, þannig að hann týnist ekki þó forritinu sé lokað._
_(10%) Hægt skal vera að leita í listanum._
- hægt að velja nákvæma leit og ónækvæma 
  - s.s í ónákvæmri færðu möguleika á að skrifa eitthvað orð og leita í öllu gagnasafni
  - og nákvæm leit færðu upp að þú getur skrifað nafn, kyn, fæðingarár og dánarár og þú getur skrifað inn í það sem þú vilt

_(10%) Þegar listinn er birtur, skal bjóða notandanum að velja hvernig hann skuli raðaður._
- raða eftir stafrófsröð alltaf, líka þegar raðað er eftir öðrum hlutum

**Þá eru gerðar eftirfarandi kröfur að auki:**

_(5%) Nota skal lagskipta högun við útfærslu kerfisins._
_(5%) Nota skal Qt Creator við útfærslu (sjá betur síðar í námskeiðinu)._
_(10%) Kóðinn skal vera lesanlegur, vel formaður, vel skjalaður, og viðhaldanlegur._
_(10%) Kóðinn skal hýstur með Git (GitHub, Bitbucket, etc.) Ath. að dæmatímakennarar/skósveinar þurfa að hafa aðgang að git geymslunni frá byrjun._
_(10%) Þátttaka hópmeðlima skal vera eins jöfn og frekast er unnt._
_(10%) Hópar hafa svigrúm til að bæta við uppgefnar kröfur, einnig er hægt að vinna sér inn stig með sérlega vel útfærðum lausnum._
- Reikna aldur fólks.

Skila skal lokaútgáfu kóðans í einni .zip/.rar skrá, ásamt upplýsingum um það hvar kóðann er að finna, þ.e. á GitHub/BitBucket etc. Þá skal fylgja með keyranleg útgáfa kerfisins, ásamt gagnaskrá með a.m.k. 10 færslum.

**Comment by SenpaiPlz** [comment]
Skil 1 - búin.
